import os
import json
from datetime import datetime
from typing import Union, List, Dict, Any, Optional, Callable
from agents.swarm import create_crawler_crew

def run_crawler_pipeline(
    model_name: Optional[str] = None,
    api_key: Optional[str] = None,
    base_url: Optional[str] = None,
    callbacks: Optional[List[Callable[[Any], Any]]] = None,
    targets: Optional[List[Dict[str, str]]] = None
) -> str:
    """
    Utility wrapper to instantly run the assembled crawler crew.

    Args:
        model_name: Optional model provider and ID (e.g. 'gemini/gemini-flash-lite-latest').
        api_key: Optional API key. Fallbacks to environment variables if not provided.
        base_url: Optional custom base gateway URL.
        callbacks: Optional list of UI callback update hooks.
        targets: Optional list of target dictionaries containing 'name' and 'url' configuration keys.

    Returns:
        The final formatted Markdown report string generated by the Formatting agent.
    """
    import time
    start_time = time.time()
    crew = create_crawler_crew(model_name, api_key, base_url, callbacks, targets)
    final_report = crew.kickoff()

    # Save structured details to output/daily_ai_news.json
    try:
        os.makedirs("output", exist_ok=True)
        
        # 0. Discovery task output (newsletters)
        discovery_output = None
        if len(crew.tasks) > 0 and crew.tasks[0].output:
            discovery_output = crew.tasks[0].output.to_dict()
        
        # 1. Extraction task output (items)
        extraction_output = None
        if len(crew.tasks) > 1 and crew.tasks[1].output:
            extraction_output = crew.tasks[1].output.to_dict()
            
        # 2. Verification task output (verified status)
        verification_output = None
        if len(crew.tasks) > 2 and crew.tasks[2].output:
            verification_output = crew.tasks[2].output.to_dict()
            
        # 3. Deduplication task output
        dedup_output = None
        if len(crew.tasks) > 3 and crew.tasks[3].output:
            dedup_output = crew.tasks[3].output.to_dict()

        # Build maps for easy lookup
        items_map = {}
        if extraction_output and "extracted_newsletters" in extraction_output:
            for newsletter in extraction_output["extracted_newsletters"]:
                for item in newsletter.get("items", []):
                    items_map[item["item_id"]] = item
                    
        verifications_map = {}
        if verification_output and "verified_items" in verification_output:
            for item in verification_output["verified_items"]:
                verifications_map[item["item_id"]] = item

        # Resolve unmerged items with full details
        resolved_unmerged = []
        if dedup_output and "unmerged_items" in dedup_output:
            for item_id in dedup_output["unmerged_items"]:
                item_details = items_map.get(item_id, {})
                verification_details = verifications_map.get(item_id, {})
                
                resolved_unmerged.append({
                    "item_id": item_id,
                    "title": item_details.get("title", item_id),
                    "type": item_details.get("type", "other"),
                    "summary": item_details.get("summary", ""),
                    "primary_source_url": verification_details.get("primary_source_url", "not verifiable"),
                    "primary_source_verification": verification_details.get("primary_source_verification", "not verified")
                })

        # Resolve canonical stories
        canonical_stories = []
        if dedup_output and "canonical_stories" in dedup_output:
            canonical_stories = dedup_output["canonical_stories"]

        date_str = datetime.now().strftime("%Y-%m-%d")
        rich_json = {
            "newsletters": discovery_output.get("newsletters", []) if discovery_output else [],
            "canonical_stories": canonical_stories,
            "unmerged_items": resolved_unmerged,
            "verified_links": verification_output.get("verified_items", []) if verification_output else []
        }

        with open(f"output/daily_ai_news_{date_str}.json", "w", encoding="utf-8") as f:
            json.dump(rich_json, f, indent=2)

        # Generate Swarm Audit Log
        total_duration = time.time() - start_time
        resolved_model = model_name or os.getenv("MODEL_NAME", "gemini/gemini-flash-lite-latest")

        # Extract token metrics if present
        token_metrics = {}
        if hasattr(crew, "usage_metrics") and crew.usage_metrics:
            try:
                token_metrics = {
                    "prompt_tokens": getattr(crew.usage_metrics, "prompt_tokens", 0),
                    "completion_tokens": getattr(crew.usage_metrics, "completion_tokens", 0),
                    "total_tokens": getattr(crew.usage_metrics, "total_tokens", 0),
                }
            except Exception:
                pass

        # Deduplication decisions list
        dedup_decisions = []
        if canonical_stories:
            for story in canonical_stories:
                story_title = story.get("title", "")
                merged_ids = story.get("merged_item_ids", [])
                if merged_ids:
                    dedup_decisions.append({
                        "canonical_story": story_title,
                        "merged_count": len(merged_ids),
                        "merged_item_ids": merged_ids
                    })

        metadata = {
            "execution_date": datetime.now().isoformat(),
            "model": resolved_model,
            "total_duration_seconds": round(total_duration, 2),
            "token_usage": token_metrics,
            "deduplication_decisions": dedup_decisions
        }

        audit_dir = "output/audit_logs"
        os.makedirs(audit_dir, exist_ok=True)

        # Save structured metadata JSON
        metadata_path = os.path.join(audit_dir, f"execution_metadata_{date_str}.json")
        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        # Save human-readable Markdown audit report
        audit_path = os.path.join(audit_dir, f"execution_audit_{date_str}.md")
        with open(audit_path, "w", encoding="utf-8") as f:
            f.write(f"# Swarm Execution Audit - {date_str}\n\n")
            f.write("## 📊 Summary Metrics\n")
            f.write(f"- **Execution Time:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"- **Total Duration:** {round(total_duration, 2)} seconds\n")
            f.write(f"- **LLM Model Configured:** `{resolved_model}`\n")
            if token_metrics:
                f.write(f"- **Prompt Tokens:** {token_metrics.get('prompt_tokens', 0):,}\n")
                f.write(f"- **Completion Tokens:** {token_metrics.get('completion_tokens', 0):,}\n")
                f.write(f"- **Total Tokens Consumed:** {token_metrics.get('total_tokens', 0):,}\n")
            f.write("\n")
            f.write("## 🔄 Deduplication Decisions\n")
            if dedup_decisions:
                f.write("| Canonical Story Title | Number of Merged Items | Merged Item IDs |\n")
                f.write("| :--- | :---: | :--- |\n")
                for dec in dedup_decisions:
                    ids_str = ", ".join(dec["merged_item_ids"])
                    f.write(f"| {dec['canonical_story']} | {dec['merged_count']} | `{ids_str}` |\n")
            else:
                f.write("No duplicate items were merged during this swarm run.\n")

    except Exception as e:
        print(f"Error generating audit logs or daily_ai_news_{date_str}.json: {e}")

    return final_report
